version: '3'
services:
    nginx1254:
      build:
        context: server/nginx/nginx-1.25.4
        dockerfile: Dockerfile
        args:
          NGINX_VERSION: ${NGINX1254_VERSION}
          NGINX_HTML: ${NGINX1254_HTML}
      ports:
        - "80:80"
        - "8080:8080"
        - "8081:8081"
      container_name: "nginx1254"
      restart: always
      volumes:
        - ${PHP_WWW_PATH}:/data/htdocs/php/:rw
        - ${NGINX1254_HTML}:/usr/share/nginx/html/:rw
        - ${PWD}/logs/server-logs/nginx/nginx-1.25.4/:/var/log/nginx/:rw
        - ${PWD}/server/nginx/nginx-1.25.4/nginx.conf:/etc/nginx/nginx.conf:rw
        - ${PWD}/server/nginx/nginx-1.25.4/conf.d:/etc/nginx/conf.d/:rw
        - ${PWD}/server/nginx/nginx-1.25.4/nginx-modules/:/usr/lib/nginx/modules/:rw
      cap_add:
          - ALL
      environment:
          RACK_ENV: development
          SESSION_SECRET:
      networks:
        local_network:
          ipv4_address: 172.172.0.10
    
    php73:
      build:
        context: server/php/php-7.3.33
        dockerfile: Dockerfile
        args:
          PHP73_PATH: ${PHP73_PATH}
          PHP73_VERSION: ${PHP73_VERSION}
          PHP_WWW_PATH: ${PHP_WWW_PATH}
          REDIS_DOWNLOAD_URL: ${REDIS_DOWNLOAD_URL}
      ports:
        - "9073:9000"
      container_name: "php73"
      restart: always
      volumes:
        - ${PHP_WWW_PATH}:/data/htdocs/php/:rw
        - ${PHP73_SITE_LOG_DIR}:/var/log/php/web:rw
        - ${PWD}/server/php/php-7.3.33/php/php.ini:/usr/local/etc/php/php.ini:rw
        - ${PWD}/server/php/php-7.3.33/php-fpm.d/:/usr/local/etc/php-fpm.d/:rw
        - ${PWD}/server/php/php-7.3.33/php-fpm.conf:/usr/local/etc/php-fpm.conf:rw
        - ${PWD}/logs/server-logs/php/php-7.3.33/php-fpm.log:/var/log/php/php-fpm.log:rw
      tty: true
      depends_on:
          - nginx1254
      networks:
        local_network:
          ipv4_address: 172.172.0.20

networks:
    local_network:
      ipam:
        driver: default
        config:
        - subnet: "172.172.0.0/24"