version: '3'
services:
    nginx:
      build:
        context: server/nginx/nginx-1.21.0
        dockerfile: Dockerfile
        args:
          NGINX_VERSION: ${NGINX_VERSION}
          NGINX_HTML: ${NGINX_HTML}
      ports: 
        - "80:80"
        - "8080:8080"
        - "8888:8888"
      container_name: "nginx121"
      restart: always
      volumes: 
        - ${NGINX_HTML}:/usr/share/nginx/html/:rw 
        - ${PHP_WWW_PATH}:/data/htdocs/www-php/:rw 
        - ${PWD}/logs/server-logs/nginx/nginx1.21.0/:/var/log/nginx/:rw
        - ${PWD}/server/nginx/nginx1.21.0/conf.d:/etc/nginx/conf.d/:rw
        - ${PWD}/server/nginx/nginx1.21.0/youxinpai:/etc/nginx/youxinpai/:rw
        - ${PWD}/server/nginx/nginx1.21.0/nginx.conf:/etc/nginx/nginx.conf:rw
        - ${PWD}/server/nginx/nginx1.21.0/nginx-modules/:/usr/lib/nginx/modules/:rw
      cap_add:
          - ALL    
      environment:
          RACK_ENV: development
          SESSION_SECRET: 
      networks:
        lampnetwork:
          ipv4_address: 172.19.0.2
        
    php74:
      build:
        context: server/php/php74
        dockerfile: Dockerfile
        args:
          PHP74_VERSION: ${PHP74_VERSION}
          PHP74_PATH: ${PHP74_PATH}
      ports: 
        - "9000:9000"    
      container_name: "php74"
      restart: always
      volumes: 
        - ${PHP_WWW_PATH}:/data/htdocs/www-php/:rw 
        - ${PWD}/server/php/php74/:/usr/local/etc/:rw
      depends_on:
          - nginx
      networks:
        lampnetwork:
          ipv4_address: 172.19.0.3

    redis625:
      build:
        context: server/redis/redis-6.2.5
        dockerfile: Dockerfile
        args:
          REDIS_VERSION: ${REDIS_VERSION}
          REDIS_DATA_PATH: ${REDIS_PATH}
      ports: 
        - "6379:6379"    
      container_name: "redis625"
      restart: always
      volumes: 
        - ${REDIS_PATH}/data/:/data/redis/:rw 
        - ${REDIS_PATH}/redis.conf:/usr/local/etc/redis.conf:rw
        - ${PWD}/logs/server-logs/redis/redis.log:/var/log/redis/redis.log:rw
      depends_on:
          - php74
      networks:
        lampnetwork:
          ipv4_address: 172.19.0.4      

networks:
    lampnetwork:
      ipam:
        driver: default
        config:
        - subnet: "172.19.0.0/16"