server {
    listen       80;
    server_name  www.xtjhfz.com xtjhfz.com;
    root         /data/htdocs/php/www.xtjhfz.com/;
    index        index.php index.htm index.html;

    ssl_protocols TLSv1.2;

    location ~ \.php$ {
;         fastcgi_pass   127.0.0.1:9000;
;         fastcgi_index  index.php;
;         fastcgi_param  SCRIPT_FILENAME   $document_root$fastcgi_script_name;
;         include        fastcgi_params;
        fastcgi_pass   php73:9000; #同一个局域网直接使用php容器
        fastcgi_index  index.php;
        fastcgi_param  SCRIPT_FILENAME  $WWW_ROOT$fastcgi_script_name;
        include        fastcgi_params;
    }

    location ~ /\.ht {
       deny all;
    }
	
    if (!-e $request_filename) {
	rewrite ^/(.*)$ /index.php?$1 last;
	break;
    }

    #日志
    #access_log  /home/logs/nginx/jhfz.log;
}
