server {
  listen 80;  
  server_name    my.aftersale.youxinpai.com;
  root /Users/liuxiaowei/Documents/youxinpai/aftersale.youxinpai.com/phpapps/aftersale/public;
  index index.php index.html;
  
  location ~* \.(jpg|jpeg|gif|css|png|js|ico|html)$ {
    access_log off;
    expires max;
  }
 
  location ~ \.php$ {
      gzip off;
      fastcgi_buffer_size 64k;
      fastcgi_buffers 4 64k;
      include fastcgi_params;
      include uxin/fastcgi_pass_php74/*;
      include uxin/yxp_cp_env/*;
  }

  location ~ /\.ht {
    deny  all;
  }
  
  if (!-e $request_filename) {
    rewrite ^/(.*)$ /index.php?$1 last;
    break;
  }
  
  #日志
  access_log /var/log/nginx/$server_name.log;
}


