server {
  listen 80;
  server_name my.agent.youxinpai.com;
  root /Users/liuxiaowei/Documents/youxinpai/agent.youxinpai.com/phpapps/agent;
  index index.php index.html;
  
  location ~* \.(jpg|jpeg|gif|css|png|js|ico)$ {
    access_log off;
    expires max;
  }
  
  location ~ \.php$ {
    include fastcgi_params;
    include uxin/fastcgi_pass_php73/*;
    include uxin/yxp_cp_env/*;
  }

  location ~ /\.ht {
    deny  all;
  }

  if (!-e $request_filename) {
    rewrite ^/(.*)$ /index.php?$1 last;
    break;
  }

  access_log /var/log/nginx/$server_name.log;
}

