server {
  listen 80;  
  server_name    my.ckapi.youxinpai.com;
  root /data/htdocs/php/ckapi.youxinpai.com/phpapps/ckapi;
  index index.php index.html;
  
  location ~* \.(jpg|jpeg|gif|css|png|js|ico|html)$ {
    access_log off;
    expires max;
  }
 
  location ~ \.php$ {
        fastcgi_pass   127.0.0.1:9000;
        fastcgi_index  index.php;
        include        youxinpai/chake_env/*;
        fastcgi_param  SCRIPT_FILENAME   $document_root$fastcgi_script_name;
        include        fastcgi_params;
  }

  location ~ /\.ht {
    deny  all;
  }
  
  if (!-e $request_filename) {
    rewrite ^/(.*)$ /index.php?$1 last;
    break;
  }
  
  #日志
  access_log /var/log/nginx/$server_name.log;
}


