server {
  listen 80;

  #listen 443 ssl;
  #ssl_certificate  /usr/local/etc/nginx/uxin/server.crt;
  #ssl_certificate_key  /usr/local/etc/nginx/server_nopwd.key;

  #keepalive_timeout 0; 
  #Multiple hostnames separated by spaces.  Replace these as well.

  server_name    my.padapi.youxinpai.com;
  root /data/htdocs/php/padapi.youxinpai.com/phpapps/padapi;
  index index.php index.html;
 
  # static file 404's aren't logged and expires header is set to maximum age
  location ~* \.(jpg|jpeg|gif|css|png|js|ico|html)$ {
    access_log off;
    expires max;
  }

  location ~ \.php$ {
	  gzip off;
	  fastcgi_buffer_size 64k;
	  fastcgi_buffers 4 64k;
    include fastcgi_params;
    include youxinpai/fastcgi_pass_php56/*;
    include youxinpai/yxp_cp_env/*;
  }
 
  location ~ /\.ht {
    deny  all;
  }

  #隐藏index.php
  if (!-e $request_filename) {
    rewrite ^/(.*)$ /index.php?$1 last;
    break;
  }

  #日志
  #error_page 404 errors/404.html;
  access_log /var/log/nginx/$server_name.log;
}


