server {
    listen       80;
    server_name  zcmt.liuxiaowei.name;
    root         /data/htdocs/php/zcmt;
    index        index.php index.html index.html;

    location ~ \.php$ {
        fastcgi_pass   php74:9000;
        fastcgi_index  index.php;
        fastcgi_param  SCRIPT_FILENAME   $document_root$fastcgi_script_name;
        include        fastcgi_params;
    }

    location ~ /\.ht {
      deny  all;
    }

    #隐藏index.php
    if (!-e $request_filename) {
      rewrite ^/(.*)$ /index.php?$1 last;
      break;
    }

    # 日志
    access_log /var/log/nginx/$server_name.log;
}
